# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_stage', models.CharField(max_length=10)),
                ('intitule', models.CharField(blank=True, max_length=100)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('places', models.IntegerField(blank=True, default=12, null=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Formateur')),
            ],
        ),
    ]
